Areas/Administrator/Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Sach.Model.Models;
using Sach.Repository;

namespace BanSachCu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class OrderDetailController : Controller
    {
        SachCuContext context = new SachCuContext();
        private OrderDetailRepository orderDetailRepo;
        public OrderDetailController()
        {
            orderDetailRepo = new OrderDetailRepository();
        }
        public IActionResult Index()
        {
            var OrderDetails = orderDetailRepo.GetAll().ToList();
            return View("Index", OrderDetails);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(OrderDetail orderDetail)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderDetailRepo.Insert(orderDetail);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(orderDetail);



        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var orderDetail = orderDetailRepo.GetById(id);
            if (orderDetail == null)
            {
                return NotFound();
            }
            return View(orderDetail);
        }

        [HttpPost]
        public IActionResult Edit(OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                context.OrderDetails.Update(orderDetail);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderDetail);
        }

        public IActionResult Delete(int id)
        {
            var orderDetail = context.OrderDetails.Find(id);
            if (orderDetail == null)
            {
                return NotFound();
            }
            context.OrderDetails.Remove(orderDetail);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Administrator/Views/OrderDetail/Create.cshtml
@model Sach.Model.Models.OrderDetail
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
<form asp-action="Create" asp-controller="OrderDetail" method="post">

    <div class="row mb-3">
        <label asp-for="OrderId" class="col-sm-2 col-form-label">Order Id</label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="OrderId">
        </div>
    </div>
    <div class="row mb-3">
        <label asp-for="ProductId" class="col-sm-2 col-form-label">Product Id</label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="ProductId">
        </div>
    </div>
    <div class="row mb-3">
        <label asp-for="Quantity" class="col-sm-2 col-form-label">Số lượng</label>
        <div class="col-sm-10">
            <textarea class="form-control" asp-for="Quantity"></textarea>
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary" href="/Administrator/OrderDetail/Index">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

Areas/Administrator/Views/OrderDetail/Index.cshtml
@model List<Sach.Model.Models.OrderDetail>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<div class="pagetitle">
    <h1>Bảng điều khiển</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Administrator" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Order Detail</li>
        </ol>
    </nav>
</div>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lưu trữ thông tin về các chi tiết đơn hàng</h5>
            <a href="/Administrator/OrderDetail/Create" class="btn btn-primary mb-2">Thêm mới</a>
            <table class="table table-bordered border-primary">
                <thead>
                    <tr>
                        <th scope="col">Mã Đơn Hàng</th>
                        <th scope="col">Mã Sản Phẩm</th>
                        <th scope="col">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td scope="row">@item.OrderId</td>
                            <td>@item.ProductId</td>
                            <td>@item.Quantity</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>