Areas/Administrator/Controllers/PublicationStatusController.cs
using Microsoft.AspNetCore.Mvc;
using Sach.Model.Models;
using Sach.Repository;

namespace BanSachCu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class PublicationStatusController : Controller
    {
        SachCuContext context = new SachCuContext();
        private PublicationStatusRepository publicationStatusRepo;
        public PublicationStatusController()
        {
            publicationStatusRepo = new PublicationStatusRepository();
        }
        public IActionResult Index()
        {
            var PublicationStatuses = publicationStatusRepo.GetAll().ToList();
            return View("Index", PublicationStatuses);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PublicationStatus publicationStatus)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    publicationStatusRepo.Insert(publicationStatus);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(publicationStatus);



        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var publicationStatus = publicationStatusRepo.GetById(id);
            if (publicationStatus == null)
            {
                return NotFound();
            }
            return View(publicationStatus);
        }

        [HttpPost]
        public IActionResult Edit(PublicationStatus publicationStatus)
        {
            if (ModelState.IsValid)
            {
                context.PublicationStatuses.Update(publicationStatus);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publicationStatus);
        }

        public IActionResult Delete(int id)
        {
            var publicationStatus = context.PublicationStatuses.Find(id);
            if (publicationStatus == null)
            {
                return NotFound();
            }
            context.PublicationStatuses.Remove(publicationStatus);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Administrator/Views/PublicationStatus/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@model Sach.Model.Models.PublicationStatus
<script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>

<form asp-action="Create" asp-controller="PublicationStatus" method="post" class="row g-3">
    <div class="col-md-2">
        <label asp-for="Id" class="form-label">ID</label>
        <input class="form-control" asp-for="Id">
    </div>
    <div class="col-md-8">
        <label asp-for="Name" class="form-label">Ngày phục chế</label>
        <input class="form-control" asp-for="Name">
    </div>
    <div class="col-6">
        <label asp-for="Description" class="form-label">Mô tả</label>
        <textarea name="editor1" class="form-control" asp-for="Description"></textarea>
        <script>
            CKEDITOR.replace('editor1');
        </script>
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary" href="/Administrator/Customer/Index">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

Areas/Administrator/Views/PublicationStatus/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
@model Sach.Model.Models.PublicationStatus

<script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
<form asp-action="Edit" asp-controller="PublicationStatus" method="post" class="row g-3">
    <div class="col-md-2">
        <label asp-for="Id" class="form-label">ID</label>
        <input class="form-control" asp-for="Id" value="@Model.Id">
    </div>
    <div class="col-md-8">
        <label asp-for="Name" class="form-label">Tên</label>
        <input class="form-control" asp-for="Name" value="@Model.Name">
    </div>
    <div class="col-6">
        <label asp-for="Description" class="form-label">Mô tả</label>
        <textarea name="editor1" class="form-control" asp-for="Description" value="@Model.Description"></textarea>
        <script>
            CKEDITOR.replace('editor1');
        </script>
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary" href="/Administrator/Customer/Index">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

Areas/Administrator/Views/PublicationStatus/Index.cshtml
@model List<Sach.Model.Models.PublicationStatus>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<div class="pagetitle">
    <h1>Bảng điều khiển</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Administrator" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Publication Status</li>
        </ol>
    </nav>
</div>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Tình trạng xuất bản của sách vào cơ sở dữ liệu của cửa hàng sách cũ</h5>
            <a href="/Administrator/PublicationStatus/Create" class="btn btn-primary mb-2">Thêm mới</a>
            <table class="table table-bordered border-primary">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Mô tả</th>
                        <th scope="col">Chỉnh sửa</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td scope="row">@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>
                                <a href="/Administrator/PublicationStatus/Edit/@item.Id" class="ri-edit-box-fill"></a>
                                <a href="/Administrator/PublicationStatus/Delete/@item.Id" class="ri-delete-bin-2-fill"></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>