Areas/Administrator/Controllers/WishListController.cs
using Microsoft.AspNetCore.Mvc;
using Sach.Model.Models;
using Sach.Repository;

namespace BanSachCu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class WishListController : Controller
    {
        SachCuContext context = new SachCuContext();
        private WishListRepository wishListRepo;
        public WishListController()
        {
            wishListRepo = new WishListRepository();
        }
        public IActionResult Index()
        {
            var WishLists = wishListRepo.GetAll().ToList();
            return View("Index", WishLists);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(WishList wishList)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    wishListRepo.Insert(wishList);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(wishList);



        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var wishList = wishListRepo.GetById(id);
            if (wishList == null)
            {
                return NotFound();
            }
            return View(wishList);
        }

        [HttpPost]
        public IActionResult Edit(WishList wishList)
        {
            if (ModelState.IsValid)
            {
                context.WishLists.Update(wishList);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wishList);
        }

        public IActionResult Delete(int id)
        {
            var wishList = context.WishLists.Find(id);
            if (wishList == null)
            {
                return NotFound();
            }
            context.WishLists.Remove(wishList);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/Administrator/Views/WishList/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@model Sach.Model.Models.WishList


<form asp-action="Create" asp-controller="WishList" method="post" class="row g-3">
    <div class="col-md-2">
        <label asp-for="Id" class="form-label">ID</label>
        <input class="form-control" asp-for="Id">
    </div>
    <div class="col-6">
        <label asp-for="CustomerId" class="form-label">Mã khách hàng</label>
        <input class="form-control" asp-for="CustomerId">
    </div>
    <div class="col-md-6">
        <label asp-for="AddedDate" class="form-label">Ngày tạo đơn</label>
        <input type="datetime-local" class="form-control" asp-for="AddedDate">
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary" href="/Administrator/WishList/Index">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

Areas/Administrator/Views/WishList/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@model List<Sach.Model.Models.WishList>

<div class="pagetitle">
    <h1>Bảng điều khiển</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Administrator" asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">WishList</li>
        </ol>
    </nav>
</div>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lưu trữ thông tin về các sản phẩm mà khách hàng muốn mua sau này</h5>
            <a href="/Administrator/WishList/Create" class="btn btn-primary mb-2">Thêm mới</a>
            <table class="table table-bordered border-primary">
                <thead>
                    <tr>
                        <th scope="col">ID</th>

                        <th scope="col">Mã Khách Hàng</th>
                        <th scope="col">Ngày thêm sản phẩm</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">@item.Id</td>
                                <td>@item.CustomerId</td>
                                <td>@item.AddedDate</td>
                               
                            </tr>
                        }

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>